version: '3.8'

services:
  backend:
    build: 
        context: .
        dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    # Define other configuration options

  frontend:
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Define other configuration options

